export const GET_COLLECTIONS_PENDING = 'GET_COLLECTIONS_PENDING';
export const GET_COLLECTIONS = 'GET_COLLECTIONS';
export const GET_COLLECTION_BY_ID = 'GET_COLLECTION_BY_ID';
export const ADD_COLLECTION = 'ADD_COLLECTION';
export const REMOVE_COLLECTION_BY_ID = 'REMOVE_COLLECTION_BY_ID';
export const UPDATE_COLLECTION_CARDS_BY_ID = 'UPDATE_COLLECTION_CARDS_BY_ID';
export const UPDATE_COLLECTION_TITLE_BY_ID = 'UPDATE_COLLECTION_TITLE_BY_ID';

export const GET_GROUPS_PENDING = 'GET_GROUPS_PENDING';
export const GET_GROUPS = 'GET_GROUPS';
export const ADD_GROUP = 'ADD_GROUP';
export const REMOVE_GROUP_BY_ID = 'REMOVE_GROUP_BY_ID';

export const GET_USER_DATA_PENDING = 'GET_USER_DATA_PENDING';
export const GET_USER_DATA = 'GET_USER_DATA';
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';


